services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-authdb}
    ports:
      - '5432:5432'
    volumes: ['pgdata:/var/lib/postgresql/data']
volumes: { pgdata: {} }
